git:
  depth: 10
sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - 9
  - 8
  - 6
  - 4
  - 10

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - node -v
  - npm -v
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - yarn test
  - codecov

after_script:
  - greenkeeper-lockfile-upload
